[package]
name = "cq-acis-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
acis-core.workspace = true
acis-py-bridge.workspace = true
pyo3.workspace = true

[features]
default = ["python-module"]
python-module = []
