from typing import Any, Sequence
from .model import AcisDiagnostic, AcisMetadata, AcisModel, BodyEntity, EntityRef, ModelEntity

from .extensions import TolerantVertex, TolerantEdge, TolerantCoedge, SubtypeTable, SupportedCurve, ResolvedSubtype, LinearSurfacePcurve, SplineSurfacePcurve

CORE_VERSION: str
def parse_sab_model(data: bytes, source_id: str = "sab-input") -> NativeModel: ...

class NativeModel:
    @staticmethod
    def from_model(model: AcisModel) -> NativeModel: ...
    def __len__(self) -> int: ...
    @property
    def metadata(self) -> AcisMetadata: ...
    @property
    def entities(self) -> tuple[ModelEntity, ...]: ...
    @property
    def diagnostics(self) -> tuple[AcisDiagnostic, ...]: ...
    def resolve(self, reference: EntityRef | int) -> ModelEntity | None: ...
    def bodies(self) -> tuple[BodyEntity, ...]: ...
    def referenced_by(self, reference: EntityRef | int) -> tuple[ModelEntity, ...]: ...
    def to_model(self) -> AcisModel: ...
    def tolerant_topology(self, reference: EntityRef | int) -> TolerantVertex | TolerantEdge | TolerantCoedge | None: ...
    @property
    def subtype_table(self) -> SubtypeTable: ...
    def resolve_subtype(self, reference: EntityRef | int) -> ResolvedSubtype | None: ...
    def linear_surface_pcurve(self, reference: EntityRef | int, surface: EntityRef | int) -> LinearSurfacePcurve | None: ...
    def supported_curve(self, reference: EntityRef | int) -> SupportedCurve | None: ...
    def spline_surface_pcurve(self, reference: EntityRef | int, surface: EntityRef | int) -> SplineSurfacePcurve | None: ...

def validate_model(model: AcisModel) -> None: ...
def resolve_index(reference: EntityRef | int, entity_count: int) -> int | None: ...
def vector(operation: str, a: tuple[float, float, float], b: tuple[float, float, float], scalar: float) -> tuple[float, float, float]: ...
def vector_scalar(operation: str, a: tuple[float, float, float], b: tuple[float, float, float]) -> float: ...
def geometry(value: ModelEntity, operation: str, parameters: Sequence[float]) -> Any: ...
